//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarLight.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientCart
    {
        public int EntryID { get; set; }
        public int ClientID { get; set; }
        public int FoodID { get; set; }
        public Nullable<int> Quanity { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual FoodMenu FoodMenu { get; set; }

        public double OverallPrice { get => (double)(Quanity * FoodMenu.Price); }
    }
}
