//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarLight.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderCarts = new HashSet<OrderCart>();
        }
    
        public int EntryID { get; set; }
        public string Name { get; set; }
        public string PhoneNum { get; set; }
        public int City { get; set; }
        public string Adress { get; set; }
        public int PaymentMethod { get; set; }
        public decimal Price { get; set; }
        public int Discount { get; set; }
        public string CardNum { get; set; }
        public Nullable<decimal> RemainderFrom { get; set; }
        public Nullable<int> ClientID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int Status { get; set; }
    
        public virtual City Cities { get; set; }
        public virtual Client Client { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual PaymentMethod PaymentMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderCart> OrderCarts { get; set; }
    }
}
