//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarLight.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservedTable
    {
        public int EntryID { get; set; }
        public int EstablishmentID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public System.DateTime ReserveDate { get; set; }
        public string Name { get; set; }
        public string PhoneNum { get; set; }
        public Nullable<int> TableNum { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Establishment Establishment { get; set; }
    }
}
